/* Shivani's birthday: a scratch-card invitation into a Korean world. */
const personalParty={sound:false,audio:null,blown:false,popped:new Set(),gateTimers:[],gateRun:0,gateStage:'invite',scratchRevealed:false,scratchObserver:null};
const partyColors=['#ff705d','#ffd45b','#74d8c2','#69aaf5','#f69ac4','#a58af0'];
function personalBirthdayContext(){return settings.personalBirthday||{active:false,occasion:'none',eventDate:new Date().getFullYear()+'-10-10',today:localDay(),timezoneLabel:'IST'};}
function shouldRenderPersonalBirthday(){return path==='/surprise'||(path==='/'&&personalBirthdayContext().active&&!new URLSearchParams(location.search).has('home'));}
function partyPreview(){return personalBirthdayContext().occasion!=='birthday';}
function partySessionKey(){return recipientStorageKey('birthday-opening-seen');}
function hasSeenBirthdayOpening(){
 if(readLocal(partySessionKey(),false))return true;
  try{if(sessionStorage.getItem(partySessionKey())==='yes')return true;if(birthdayRecipient().name.toLowerCase()==='shivani')for(let i=0;i<sessionStorage.length;i++){const key=sessionStorage.key(i);if((key.startsWith('birthday-party-v2:')||key.startsWith('birthday-opening:'))&&sessionStorage.getItem(key)){writeLocal(partySessionKey(),true);return true;}}}catch{}
 return false;
}
function motionIsReduced(){return matchMedia('(prefers-reduced-motion: reduce)').matches;}
function partyCake(){return `<div class="birthday-sculpture" aria-hidden="true"><span class="cake-orbit"></span><span class="cake-spark spark-coral">✳</span><span class="cake-spark spark-blue">✦</span><span class="cake-sticker">시바니<br>SHIVANI</span><div class="party-cake"><div class="party-candle candle-left"><i></i></div><div class="party-candle candle-middle"><i></i></div><div class="party-candle candle-right"><i></i></div><div class="party-cake-side"><span>생일 축하해 ♡</span></div><div class="party-cake-top"><span>♡</span></div><div class="party-icing"><b></b><b></b><b></b><b></b><b></b><b></b></div><div class="cake-sprinkles"><i></i><i></i><i></i><i></i><i></i><i></i></div></div><div class="birthday-pedestal"></div><span class="cake-handwriting">a little birthday wish for Shivani.</span></div>`;}
function renderPersonalBirthday(){renderShivaniBirthday();}
function setupBirthdayScratch(){
 const canvas=document.querySelector('#birthday-scratch-canvas');if(!canvas||personalParty.scratchRevealed)return;
 const box=canvas.getBoundingClientRect();if(!box.width)return;let context;try{context=canvas.getContext('2d');}catch{return;}if(!context)return;
 const ratio=Math.min(devicePixelRatio||1,2),width=Math.round(box.width*ratio),height=Math.round(box.height*ratio),signature=birthdayRecipient().name+'|'+birthdayRecipient().koreanName;if(canvas.dataset.bound&&canvas.width===width&&canvas.height===height&&canvas.dataset.recipient===signature)return;
 canvas.width=width;canvas.height=height;context.setTransform(ratio,0,0,ratio,0,0);context.globalCompositeOperation='source-over';
 const gradient=context.createLinearGradient(0,0,box.width,box.height);gradient.addColorStop(0,'#a8ccef');gradient.addColorStop(.4,'#9bded2');gradient.addColorStop(.7,'#ffe395');gradient.addColorStop(1,'#f5b4d0');context.fillStyle=gradient;context.fillRect(0,0,box.width,box.height);
 context.strokeStyle='rgba(255,255,255,.35)';context.lineWidth=1;for(let x=-box.height;x<box.width;x+=18){context.beginPath();context.moveTo(x,0);context.lineTo(x+box.height,box.height);context.stroke();}
 const headline=birthdayText('SHIVANI, THIS IS FOR YOU');context.fillStyle='#24495b';context.textAlign='center';let size=24;context.font='800 '+size+'px sans-serif';while(context.measureText(headline).width>box.width-30&&size>10){size--;context.font='800 '+size+'px sans-serif';}context.fillText(headline,box.width/2,box.height/2-12,box.width-24);context.font='13px sans-serif';context.fillText('긁어서 선물을 찾아봐 · scratch here ♡',box.width/2,box.height/2+22);canvas.dataset.recipient=signature;
 if(canvas.dataset.bound)return;canvas.dataset.bound='yes';let drawing=false,last=null;
 function point(event){const rect=canvas.getBoundingClientRect();return{x:(event.clientX-rect.left)*canvas.width/rect.width,y:(event.clientY-rect.top)*canvas.height/rect.height};}
 function erase(event){if(!drawing||personalParty.scratchRevealed)return;const next=point(event),ctx=canvas.getContext('2d');ctx.save();ctx.setTransform(1,0,0,1,0,0);ctx.globalCompositeOperation='destination-out';ctx.lineWidth=44*Math.min(devicePixelRatio||1,2);ctx.lineCap='round';ctx.beginPath();ctx.moveTo((last||next).x,(last||next).y);ctx.lineTo(next.x,next.y);ctx.stroke();ctx.beginPath();ctx.arc(next.x,next.y,ctx.lineWidth/2,0,Math.PI*2);ctx.fill();ctx.restore();last=next;}
 canvas.addEventListener('pointerdown',event=>{drawing=true;last=null;canvas.setPointerCapture(event.pointerId);erase(event);});canvas.addEventListener('pointermove',erase);
 const finish=()=>{if(!drawing)return;drawing=false;last=null;const sample=document.createElement('canvas');sample.width=64;sample.height=40;const ctx=sample.getContext('2d');ctx.drawImage(canvas,0,0,64,40);const data=ctx.getImageData(0,0,64,40).data;let clear=0;for(let i=3;i<data.length;i+=4)if(data[i]<60)clear++;if(clear/(64*40)>.30)revealScratchWish();};canvas.addEventListener('pointerup',finish);canvas.addEventListener('pointercancel',finish);
 if('ResizeObserver'in window){let previous=box.width;personalParty.scratchObserver=new ResizeObserver(entries=>{const current=entries[0].contentRect.width;if(Math.abs(current-previous)>1&&!personalParty.scratchRevealed){previous=current;setupBirthdayScratch();}});personalParty.scratchObserver.observe(canvas.parentElement);}
}
function revealScratchWish(){if(personalParty.scratchRevealed)return;personalParty.scratchRevealed=true;document.querySelector('.birthday-scratch-card')?.classList.add('is-revealed');personalParty.scratchObserver?.disconnect();unlockKoreaGift(true);}
function syncPersonalBirthdayUI(){
 const context=personalBirthdayContext(),label=document.querySelector('#party-preview-label');if(label)label.textContent=partyPreview()?'Preview mode · Shivani’s birthday celebration activates on 10 October, IST.':'';
 const ribbon=document.querySelector('#personal-birthday-ribbon');if(context.active&&!document.body.classList.contains('personal-birthday')&&path!=='/sorry'){if(!ribbon){const link=document.createElement('a');link.id='personal-birthday-ribbon';link.className='personal-birthday-ribbon';link.href='/surprise';link.textContent='🫰 Shivani’s birthday world · 시바니의 생일 여행 ↗';document.querySelector('.site-header').after(link);}}else ribbon?.remove();
  syncKoreanGift();
  applyBirthdayRecipient();
}
function bindPartySound(root){root.querySelectorAll('[data-party-sound]').forEach(button=>button.onclick=async()=>{personalParty.sound=!personalParty.sound;if(personalParty.sound){try{const Audio=window.AudioContext||window.webkitAudioContext;if(!Audio)throw new Error();if(!personalParty.audio)personalParty.audio=new Audio();await personalParty.audio.resume();playPartyChime();}catch{personalParty.sound=false;toast('Your celebration works without sound too. ♡');}}document.querySelectorAll('[data-party-sound]').forEach(b=>{b.setAttribute('aria-pressed',String(personalParty.sound));b.textContent=personalParty.sound?'Sound on ♫':'Sound off ♫';});});}
function playPartyChime(frequency){const audio=personalParty.audio;if(!personalParty.sound||!audio||audio.state!=='running')return;(frequency?[frequency]:[523.25,659.25,783.99,1046.5]).forEach((value,index)=>{const oscillator=audio.createOscillator(),gain=audio.createGain(),start=audio.currentTime+index*.09;oscillator.type='sine';oscillator.frequency.value=value;gain.gain.setValueAtTime(.0001,start);gain.gain.exponentialRampToValueAtTime(.04,start+.02);gain.gain.exponentialRampToValueAtTime(.0001,start+.55);oscillator.connect(gain);gain.connect(audio.destination);oscillator.start(start);oscillator.stop(start+.6);oscillator.onended=()=>{oscillator.disconnect();gain.disconnect();};});}
function partyConfetti(){if(motionIsReduced())return;document.querySelector('.personal-confetti')?.remove();const layer=document.createElement('div');layer.className='personal-confetti';layer.setAttribute('aria-hidden','true');for(let i=0;i<64;i++){const piece=document.createElement('span');piece.textContent=['✦','♡','✳','·'][i%4];piece.style.setProperty('--confetti-x',Math.random()*100+'vw');piece.style.setProperty('--confetti-delay',Math.random()*.8+'s');piece.style.setProperty('--confetti-size',9+Math.random()*18+'px');piece.style.setProperty('--confetti-turn',(-190+Math.random()*380)+'deg');piece.style.color=partyColors[i%partyColors.length];layer.append(piece);}(document.querySelector('#birthday-gate[open]')||document.body).append(layer);setTimeout(()=>layer.remove(),4200);}
function clearBirthdayGateTimers(){personalParty.gateTimers.forEach(clearTimeout);personalParty.gateTimers=[];personalParty.gateRun++;}
function openBirthdayGate(force=false){
 if(!document.body.classList.contains('personal-birthday'))return;
 const query=new URL(location.href);if(query.searchParams.get('replay')==='1'){force=true;query.searchParams.delete('replay');history.replaceState(null,'',query.pathname+query.search+query.hash);}
 if(!force&&hasSeenBirthdayOpening())return;
 clearTimeout(arrivalTimer);document.querySelector('.arrival')?.remove();clearBirthdayGateTimers();personalParty.popped.clear();
 let gate=document.querySelector('#birthday-gate');if(!gate){gate=document.createElement('dialog');gate.id='birthday-gate';gate.setAttribute('aria-labelledby','birthday-gate-title');gate.innerHTML='<div class="gate-topbar"><span>FOR SHIVANI · 시바니에게 <b>10 / 10</b></span><div><button type="button" data-party-sound aria-pressed="false">Sound off ♫</button><button type="button" id="skip-birthday-gate">Skip to your gift ↗</button></div></div><div class="gate-sky" aria-hidden="true"><i>✳</i><i>✦</i><i>♡</i><i>✳</i><i>✦</i><i>✺</i></div><div id="birthday-gate-stage"></div><div class="gate-footer">HAPPY BIRTHDAY SHIVANI · 시바니, 생일 축하해!</div>';document.body.append(gate);bindPartySound(gate);gate.querySelector('#skip-birthday-gate').onclick=()=>closeBirthdayGate(false);gate.addEventListener('cancel',event=>{event.preventDefault();closeBirthdayGate(false);});}
  renderGateStage('invite');applyBirthdayRecipient(gate);if(!gate.open)gate.showModal();gate.querySelector('#unwrap-birthday').focus({preventScroll:true});
}
function renderGateStage(stage){const gate=document.querySelector('#birthday-gate'),root=document.querySelector('#birthday-gate-stage');if(!root)return;personalParty.gateStage=stage;gate.dataset.stage=stage;
 if(stage==='invite'){root.innerHTML='<div class="gate-invitation"><div class="secret-ticket"><span>SPECIAL DELIVERY FOR</span><strong>SHIVANI!</strong><div><b>시바니에게</b><i>10:10</i><b>ONLY FOR YOU</b></div><span class="ticket-star" aria-hidden="true">♡</span></div><h2 id="birthday-gate-title">Shivani, your birthday<br>has a <em>little secret.</em></h2><p>시바니, 준비됐어?<br>A birthday gift is waiting on the other side.</p><button class="party-button" id="unwrap-birthday">Let’s find it <span>시작 ↗</span></button></div>';root.querySelector('#unwrap-birthday').onclick=()=>{renderGateStage('balloons');root.querySelector('[data-balloon]')?.focus();};}
 if(stage==='balloons'){root.innerHTML=`<div class="balloon-game"><span class="gate-step-label">FOR SHIVANI / 오직 시바니를 위해</span><h2 id="birthday-gate-title">A little birthday sparkle.<br><em>Pop to reveal it.</em></h2><div class="birthday-balloons">${['HAPPY','BIRTHDAY','SHIVANI'].map((word,i)=>`<button type="button" class="birthday-balloon balloon-${i}" data-balloon="${i}" aria-label="Pop balloon ${i+1}" aria-pressed="false"><span class="balloon-shape" aria-hidden="true"><i>${i+1}</i></span><span class="balloon-word">${word}</span><span class="balloon-string" aria-hidden="true"></span></button>`).join('')}</div><p id="balloon-progress" role="status">0 / 3 · 풍선을 터뜨려 봐</p></div>`;root.querySelectorAll('[data-balloon]').forEach(button=>button.onclick=()=>popBirthdayBalloon(button));}
 if(stage==='countdown')root.innerHTML='<div class="birthday-countdown"><span class="gate-step-label">READY, SHIVANI? / 시바니, 준비됐어?</span><h2 id="birthday-gate-title" class="sr-only">Your birthday reveal is starting</h2><strong id="birthday-countdown-number" aria-live="polite">3</strong><p>A little celebration, just for you.</p></div>';
 if(stage==='reveal'){root.innerHTML='<div class="birthday-grand-reveal"><span class="reveal-sticker">시바니, 생일 축하해!</span><h2 id="birthday-gate-title"><span>HAPPY</span><span>BIRTHDAY,</span><em>SHIVANI!</em></h2><p>시바니를 위해 준비한 생일 선물이야.<br>A birthday gift, made just for you.</p><button class="party-button" id="enter-birthday-party">Open Shivani’s gift <span>선물 열기 ↗</span></button></div>';partyConfetti();playPartyChime();root.querySelector('#enter-birthday-party').onclick=()=>closeBirthdayGate(true);root.querySelector('#enter-birthday-party').focus({preventScroll:true});}
}
function popBirthdayBalloon(button){const index=Number(button.dataset.balloon);if(personalParty.popped.has(index))return;personalParty.popped.add(index);button.classList.add('popped');button.setAttribute('aria-pressed','true');button.disabled=true;playPartyChime([523.25,659.25,783.99][index]);document.querySelector('#balloon-progress').textContent=personalParty.popped.size+' / 3 · '+(personalParty.popped.size===3?'Happy birthday, Shivani!':'계속해 봐 ♡');if(personalParty.popped.size===3){const run=personalParty.gateRun;personalParty.gateTimers.push(setTimeout(()=>{if(run===personalParty.gateRun&&document.querySelector('#birthday-gate')?.open)startBirthdayCountdown();},motionIsReduced()?0:450));}else document.querySelector('[data-balloon]:not([disabled])')?.focus({preventScroll:true});}
function startBirthdayCountdown(){if(motionIsReduced()){renderGateStage('reveal');return;}renderGateStage('countdown');const run=personalParty.gateRun;[2,1,0].forEach((number,index)=>personalParty.gateTimers.push(setTimeout(()=>{if(run!==personalParty.gateRun||!document.querySelector('#birthday-gate')?.open)return;if(number===0){renderGateStage('reveal');return;}const label=document.querySelector('#birthday-countdown-number');if(label){label.textContent=number;label.classList.remove('countdown-tick');void label.offsetWidth;label.classList.add('countdown-tick');playPartyChime(330+number*110);}},(index+1)*720)));}
function closeBirthdayGate(celebrate){const gate=document.querySelector('#birthday-gate');if(!gate?.open)return;clearBirthdayGateTimers();gate.close();writeLocal(partySessionKey(),true);try{sessionStorage.setItem(partySessionKey(),'yes');}catch{}document.querySelector('#personal-birthday-heading')?.focus({preventScroll:true});if(celebrate)partyConfetti();}
function downloadPersonalBirthdayCard(){
 const year=personalBirthdayContext().eventDate.slice(0,4),recipient=birthdayRecipient();
 const fontSize=text=>Math.max(8,Math.min(110,Math.floor(720/Math.max(1,Array.from(text).reduce((sum,c)=>sum+(c.codePointAt(0)>255?1:.68),0)))));
 const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="900" height="1200" viewBox="0 0 900 1200"><rect width="900" height="1200" rx="30" fill="#fff8ee"/><circle cx="740" cy="190" r="270" fill="#f7c5d2"/><circle cx="90" cy="1050" r="280" fill="#b8dfd4"/><rect x="45" y="45" width="810" height="1110" rx="18" fill="none" stroke="#b8cfc7" stroke-width="2"/><g text-anchor="middle" font-family="Arial,sans-serif" fill="#244e55"><text x="450" y="180" font-size="27" letter-spacing="5">HAPPY BIRTHDAY</text><text x="450" y="355" font-size="${fontSize(recipient.name.toUpperCase())}" font-weight="900">${esc(recipient.name.toUpperCase())}</text><text x="450" y="525" font-size="${fontSize(recipient.koreanName)}" font-weight="700">${esc(recipient.koreanName)}</text><text x="450" y="660" font-size="40">생일 축하해!</text><text x="450" y="815" font-size="80" fill="#e995a1">♡</text><text x="450" y="975" font-size="28">A Korean birthday world, just for you.</text><text x="450" y="1060" font-size="24">10 OCTOBER ${esc(year)}</text></g></svg>`;
 const url=URL.createObjectURL(new Blob([svg],{type:'image/svg+xml;charset=utf-8'})),link=document.createElement('a');link.href=url;link.download=birthdayFileName()+'-korean-birthday-'+year+'.svg';document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);
}
